import 'package:drift/drift.dart';

/// Stores professional recommendations generated by the local rule engine
/// and/or AI narrative analysis.
///
/// Indexed on survey_id for efficient retrieval when exporting reports
/// or displaying the recommendations sheet.
class SurveyRecommendations extends Table {
  TextColumn get id => text()();
  TextColumn get surveyId => text()();
  TextColumn get category => text()();
  TextColumn get severity => text()();
  TextColumn get screenId => text()();
  TextColumn get fieldId => text().nullable()();
  TextColumn get reason => text()();
  TextColumn get suggestedText => text()();
  BoolColumn get accepted => boolean().withDefault(const Constant(false))();
  DateTimeColumn get createdAt => dateTime()();

  // v17: Hybrid intelligence audit columns
  TextColumn get sourceType => text().withDefault(const Constant('rule'))();
  TextColumn get ruleVersion => text().nullable()();
  TextColumn get aiModelVersion => text().nullable()();
  RealColumn get confidenceScore => real().nullable()();
  IntColumn get generationTimestamp => integer().nullable()();
  TextColumn get internalReasoning => text().nullable()();
  TextColumn get auditHash => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
