import 'package:drift/drift.dart';

/// Stores quality scores generated by the hybrid intelligence engine.
///
/// Four dimensions: compliance, narrative strength, risk exposure, overall.
/// Scores are percentages (0.0–100.0).
class SurveyQualityScores extends Table {
  TextColumn get id => text()();
  TextColumn get surveyId => text()();
  RealColumn get complianceScore => real()();
  RealColumn get narrativeScore => real()();
  RealColumn get riskScore => real()();
  RealColumn get overallScore => real()();
  DateTimeColumn get generatedAt => dateTime()();
  TextColumn get engineVersion => text()();

  @override
  Set<Column> get primaryKey => {id};
}
