import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:equatable/equatable.dart';

/// Categories of professional recommendations aligned with RICS standards.
enum RecommendationCategory {
  compliance('Compliance'),
  narrativeStrength('Narrative Strength'),
  riskClarification('Risk Clarification'),
  dataGaps('Data Gaps'),
  valuationJustification('Valuation Justification');

  const RecommendationCategory(this.displayName);
  final String displayName;
}

/// Severity levels for recommendations.
enum RecommendationSeverity {
  high('High'),
  moderate('Moderate'),
  low('Low');

  const RecommendationSeverity(this.displayName);
  final String displayName;
}

/// Source of a recommendation — deterministic rule engine or AI analysis.
enum RecommendationSource {
  rule('Rule Engine'),
  ai('Professional Analysis');

  const RecommendationSource(this.displayName);
  final String displayName;

  String get key => name;

  static RecommendationSource fromKey(String key) => switch (key) {
        'ai' => RecommendationSource.ai,
        _ => RecommendationSource.rule,
      };
}

/// A single professional recommendation generated by the hybrid engine.
class ProfessionalRecommendation extends Equatable {
  const ProfessionalRecommendation({
    required this.id,
    required this.category,
    required this.severity,
    required this.screenId,
    this.fieldId,
    required this.reason,
    required this.suggestedText,
    this.accepted = false,
    this.source = RecommendationSource.rule,
    this.ruleVersion,
    this.aiModelVersion,
    this.confidenceScore,
    this.internalReasoning,
    this.auditHash,
  });

  final String id;
  final RecommendationCategory category;
  final RecommendationSeverity severity;
  final String screenId;
  final String? fieldId;
  final String reason;
  final String suggestedText;
  final bool accepted;

  // Hybrid intelligence audit fields
  final RecommendationSource source;
  final String? ruleVersion;
  final String? aiModelVersion;
  final double? confidenceScore;
  final String? internalReasoning;
  final String? auditHash;

  /// Generate a SHA-256 audit hash for legal defensibility.
  static String computeAuditHash({
    required String category,
    required String severity,
    required String screenId,
    required String reason,
    required String suggestedText,
    required String source,
    String? ruleVersion,
  }) {
    final payload = '$category|$severity|$screenId|$reason|$suggestedText|$source|${ruleVersion ?? ''}';
    return sha256.convert(utf8.encode(payload)).toString().substring(0, 16);
  }

  ProfessionalRecommendation copyWith({
    String? id,
    RecommendationCategory? category,
    RecommendationSeverity? severity,
    String? screenId,
    String? fieldId,
    String? reason,
    String? suggestedText,
    bool? accepted,
    RecommendationSource? source,
    String? ruleVersion,
    String? aiModelVersion,
    double? confidenceScore,
    String? internalReasoning,
    String? auditHash,
  }) {
    return ProfessionalRecommendation(
      id: id ?? this.id,
      category: category ?? this.category,
      severity: severity ?? this.severity,
      screenId: screenId ?? this.screenId,
      fieldId: fieldId ?? this.fieldId,
      reason: reason ?? this.reason,
      suggestedText: suggestedText ?? this.suggestedText,
      accepted: accepted ?? this.accepted,
      source: source ?? this.source,
      ruleVersion: ruleVersion ?? this.ruleVersion,
      aiModelVersion: aiModelVersion ?? this.aiModelVersion,
      confidenceScore: confidenceScore ?? this.confidenceScore,
      internalReasoning: internalReasoning ?? this.internalReasoning,
      auditHash: auditHash ?? this.auditHash,
    );
  }

  @override
  List<Object?> get props => [
        id, category, severity, screenId, fieldId,
        reason, suggestedText, accepted, source,
        ruleVersion, aiModelVersion, confidenceScore,
        internalReasoning, auditHash,
      ];
}

/// Quality scores for a survey (percentages 0–100).
class QualityScores extends Equatable {
  const QualityScores({
    required this.complianceScore,
    required this.narrativeScore,
    required this.riskScore,
    required this.overallScore,
  });

  final double complianceScore;
  final double narrativeScore;
  final double riskScore;
  final double overallScore;

  @override
  List<Object?> get props => [complianceScore, narrativeScore, riskScore, overallScore];
}

/// Result of running the hybrid recommendation engine against a survey.
class ProfessionalRecommendationsResult extends Equatable {
  const ProfessionalRecommendationsResult({
    required this.surveyId,
    required this.recommendations,
    required this.generatedAt,
    required this.engineVersion,
    this.scores,
  });

  final String surveyId;
  final List<ProfessionalRecommendation> recommendations;
  final DateTime generatedAt;
  final String engineVersion;
  final QualityScores? scores;

  List<ProfessionalRecommendation> byCategory(RecommendationCategory c) =>
      recommendations.where((r) => r.category == c).toList();

  List<ProfessionalRecommendation> bySource(RecommendationSource s) =>
      recommendations.where((r) => r.source == s).toList();

  int get highCount =>
      recommendations.where((r) => r.severity == RecommendationSeverity.high).length;

  int get moderateCount =>
      recommendations.where((r) => r.severity == RecommendationSeverity.moderate).length;

  int get lowCount =>
      recommendations.where((r) => r.severity == RecommendationSeverity.low).length;

  int get acceptedCount => recommendations.where((r) => r.accepted).length;

  int get ruleCount => bySource(RecommendationSource.rule).length;
  int get aiCount => bySource(RecommendationSource.ai).length;

  bool get isEmpty => recommendations.isEmpty;

  ProfessionalRecommendationsResult copyWith({
    List<ProfessionalRecommendation>? recommendations,
    QualityScores? scores,
  }) {
    return ProfessionalRecommendationsResult(
      surveyId: surveyId,
      recommendations: recommendations ?? this.recommendations,
      generatedAt: generatedAt,
      engineVersion: engineVersion,
      scores: scores ?? this.scores,
    );
  }

  @override
  List<Object?> get props => [surveyId, recommendations, generatedAt, engineVersion, scores];
}
