import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../domain/repositories/ai_repository.dart' as repo;
import '../providers/ai_providers.dart';
import 'ai_action_button.dart';
import 'ai_result_sheet.dart';

/// AI disclaimers for different features
class AiDisclaimers {
  static const report =
      'This AI-generated narrative is intended as a drafting aid only. '
      'It must be reviewed, verified, and edited by a qualified surveyor '
      'before inclusion in any professional report. The AI cannot physically '
      'inspect the property and may not accurately reflect actual conditions.';

  static const recommendations =
      'These recommendations are generated by AI based on reported issues '
      'and should be treated as suggestions only. A qualified surveyor must '
      'validate all recommendations before advising clients.';

  static const riskSummary =
      'This risk summary is AI-generated for illustrative purposes only. '
      'It does not constitute professional advice. A qualified surveyor must '
      'review and validate all risk assessments.';

  static const consistency =
      'Consistency issues identified by AI are suggestions only. Some flagged '
      'items may be intentional or context-appropriate. A qualified surveyor '
      'should review all items before making changes.';

  static const photoTags =
      'Photo tags and descriptions are AI-generated suggestions only. '
      'A qualified surveyor should verify all tags and associations.';
}

/// A card widget for displaying AI-generated summary with generate button
class AiSummaryCard extends ConsumerWidget {
  const AiSummaryCard({
    required this.title,
    required this.surveyId,
    required this.propertyAddress,
    this.propertyType,
    this.sections = const [],
    this.issues = const [],
    this.onSummaryAccepted,
    super.key,
  });

  final String title;
  final String surveyId;
  final String propertyAddress;
  final String? propertyType;
  final List<repo.SectionAnswersInput> sections;
  final List<repo.IssueInput> issues;
  final ValueChanged<String>? onSummaryAccepted;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final aiStatus = ref.watch(aiStatusProvider);
    final reportState = ref.watch(aiReportNotifierProvider);

    return Card(
      elevation: 0,
      color: theme.colorScheme.primaryContainer.withOpacity(0.15),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
        side: BorderSide(
          color: theme.colorScheme.primaryContainer,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: theme.colorScheme.primaryContainer,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Icon(
                    Icons.auto_awesome,
                    size: 18,
                    color: theme.colorScheme.onPrimaryContainer,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        title,
                        style: theme.textTheme.titleSmall?.copyWith(
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      Text(
                        'Powered by AI',
                        style: theme.textTheme.labelSmall?.copyWith(
                          color: theme.colorScheme.primary,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Text(
              'Generate an AI-assisted summary based on your inspection data. '
              'You can review and edit before using.',
              style: theme.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.onSurfaceVariant,
              ),
            ),
            const SizedBox(height: 16),
            aiStatus.when(
              data: (status) {
                if (!status.available) {
                  return const AiUnavailableMessage();
                }
                return SizedBox(
                  width: double.infinity,
                  child: AiActionButton(
                    label: 'Generate AI Summary',
                    isLoading: reportState.isLoading,
                    onPressed: () => _generateSummary(context, ref),
                  ),
                );
              },
              loading: () => const SizedBox(
                width: double.infinity,
                child: AiButtonSkeleton(),
              ),
              error: (_, __) => const AiUnavailableMessage(),
            ),
            if (reportState.isLoading) ...[
              const SizedBox(height: 8),
              Row(
                children: [
                  SizedBox(
                    width: 12,
                    height: 12,
                    child: CircularProgressIndicator(
                      strokeWidth: 1.5,
                      color: theme.colorScheme.primary,
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      'AI is analysing your inspection data. This may take up to 30 seconds...',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: theme.colorScheme.onSurfaceVariant,
                        fontStyle: FontStyle.italic,
                      ),
                    ),
                  ),
                ],
              ),
            ],
            if (reportState.error != null && !reportState.isLoading) ...[
              const SizedBox(height: 8),
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: reportState.isServiceUnavailable
                      ? theme.colorScheme.tertiaryContainer.withOpacity(0.3)
                      : theme.colorScheme.errorContainer.withOpacity(0.3),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Row(
                  children: [
                    Icon(
                      reportState.isServiceUnavailable
                          ? Icons.cloud_off_rounded
                          : Icons.error_outline,
                      size: 16,
                      color: reportState.isServiceUnavailable
                          ? theme.colorScheme.onTertiaryContainer
                          : theme.colorScheme.error,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        _formatError(reportState.error!, reportState.isServiceUnavailable),
                        style: theme.textTheme.bodySmall?.copyWith(
                          color: reportState.isServiceUnavailable
                              ? theme.colorScheme.onTertiaryContainer
                              : theme.colorScheme.error,
                        ),
                      ),
                    ),
                    TextButton(
                      onPressed: () => _generateSummary(context, ref),
                      style: TextButton.styleFrom(
                        padding: const EdgeInsets.symmetric(horizontal: 8),
                        minimumSize: Size.zero,
                        tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                      ),
                      child: const Text('Retry'),
                    ),
                  ],
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Future<void> _generateSummary(BuildContext context, WidgetRef ref) async {
    final notifier = ref.read(aiReportNotifierProvider.notifier);

    // Build the request from provided data
    final request = repo.GenerateReportRequest(
      surveyId: surveyId,
      propertyAddress: propertyAddress,
      propertyType: propertyType,
      sections: sections,
      issues: issues,
    );

    await notifier.generateReport(request);

    final state = ref.read(aiReportNotifierProvider);

    if (!context.mounted) return;

    if (state.hasResponse && state.response != null) {
      final accepted = await AiResultSheet.show(
        context: context,
        title: 'AI Summary',
        content: state.response!.executiveSummary,
        disclaimer: AiDisclaimers.report,
        onRetry: () => _generateSummary(context, ref),
      );

      if (accepted == true && onSummaryAccepted != null) {
        onSummaryAccepted!(state.response!.executiveSummary);
      }
    } else if (state.error != null) {
      AiErrorSheet.show(
        context: context,
        title: 'Generation Failed',
        errorMessage: _formatError(state.error!),
        onRetry: () => _generateSummary(context, ref),
      );
    }
  }

  String _formatError(String error, [bool isServiceUnavailable = false]) {
    if (isServiceUnavailable) {
      return 'AI service is temporarily unavailable. Please try again in a few moments.';
    }
    if (error.contains('TimeoutException') || error.contains('timed out')) {
      return 'The request took too long. The AI model may be under heavy load. Please try again.';
    }
    if (error.contains('timeout') || error.contains('Timeout')) {
      return 'The request timed out. Please try again.';
    }
    if (error.contains('network') || error.contains('Network')) {
      return 'Network error. Please check your connection and try again.';
    }
    if (error.contains('quota') || error.contains('Quota')) {
      return 'AI usage quota exceeded. Please try again later.';
    }
    if (error.contains('503') || error.contains('service unavailable')) {
      return 'AI service is temporarily unavailable. Please try again in a few moments.';
    }
    if (error.contains('circuit')) {
      return 'AI service is recovering from errors. Please try again in a minute.';
    }
    return 'Something went wrong. Please try again.';
  }
}

// Re-export repository types for convenience
typedef SectionAnswersInput = repo.SectionAnswersInput;
typedef IssueInput = repo.IssueInput;
